CREATE TABLE IF NOT EXISTS users(
username VARCHAR(50) PRIMARY KEY,
email VARCHAR(50) NOT NULL,
password CHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS notes(
id SERIAL PRIMARY KEY,
title VARCHAR(50) NOT NULL,
content TEXT NOT NULL,
username VARCHAR(50) NOT NULL,
category VARCHAR(50) NOT NULL
);