CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(50) PRIMARY KEY,
    email VARCHAR(50) NOT NULL UNIQUE,
    password CHAR(60) NOT NULL CHECK (LENGTH(password) = 60),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notes (
    id SERIAL PRIMARY KEY,
    title VARCHAR(50) NOT NULL CHECK (LENGTH(TRIM(title)) > 0),
    content TEXT NOT NULL,
    username VARCHAR(50) NOT NULL REFERENCES users(username),
    category VARCHAR(50) NOT NULL DEFAULT 'uncategorized',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS note_permissions(
    note_id INTEGER REFERENCES notes(id) ON DELETE CASCADE,
    username VARCHAR(50) REFERENCES users(username) ON DELETE CASCADE,
    can_edit BOOLEAN NOT NULL DEFAULT false,
    can_read BOOLEAN NOT NULL DEFAULT true,
    PRIMARY KEY (note_id, username)
);

-- TODO: communities table
-- TODO: friends table
